version: '3.8'
services:
  api:
    build: .
    container_name: modart-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/modart?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: modart-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: modart
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge